app:
  name: 'goph-keeper-server'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'goph-keeper-server'

postgres:
  DSN: 'postgres://postgres:postgres@localhost:5454/gophkeeper_server?sslmode=disable'

security:
  access_token_expired_in: '60m'
  access_token_maxage: 60
  refresh_token_expired_in: '60m'
  refresh_token_maxage: 60
  domain: 'localhost'

cache:
  default_expiration: 5
  cleanup_interval: 10

files_storage:
  location: 'users_files'