app:
  name: 'gophkeeper-client'
  version: '1.0.0'

server:
  url: 'http://localhost:8080'

logger:
  log_level: 'debug'
  rollbar_env: 'gophkeeper-client'

storage:
  driver: mock
  postgres:
    dsn: 'postgres://postgres:postgres@postgres:5454/gophkeeper?sslmode=disable'